### PR TITLE
Add SRI and security headers

### PR DESCRIPTION
**Pull request by g-k**
TODO / need help with:
- [ ] test the nginx config (the CSP header was tested using flask-csp but the other weren't)
- [ ] find out where to log CSP violations

Changes to analysis-service:
* Add [subresource integrity/SRI](https://w3c.github.io/webappsec-subresource-integrity/) hashes to 3rd party JS scripts 
  * excluding Persona include.js which we trust with auth (adding a SRI hash with `crossorigin` set to `anonymous` or `use-credentials` causes the error `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://login.persona.org/include.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://login.persona.org’).`)
  * changed the CDN from `ajax.aspnetcdn.com` to `cdnjs.cloudflare.com`
* Add a report only CSP header
  * need `unsafe-line` for style-src until we can upgrade jQuery see also: https://github.com/toolness/fleeting/issues/9
  * Persona makes an iframe for communication
* Move inline JS to separate files so we don't need `unsafe-line` scripts 
  * this will require manually updating the Flask-BrowserID `auth_script` template variable if it changes
* Add older security headers for XSS protection, frame options, and content-type, and [cache control](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Web_Content_Caching)
  * assuming the site isn't iframed someplace else

Functional Tests checking for CSP violations and other errors (after stubbing out the AWS resources):

- [x] GET /
- [x] log in w/ Persona
- [x] GET /cluster
- [x] GET cluster/monitor/test-cluster-id
- [x] GET /cluster/schedule
- [x] GET /worker
- [x] GET /schedule
- [x] log out w/ Persona
- [x] modify the version of a resource with an SRI hash and check that it causes an error

### CODE REVIEW

**Comment by vitillo** [comment]
We appreciate the contribution but the analysis service is about to be deprecated and because of that we are not accepting any patches. See this [repository](https://github.com/mozilla/telemetry-analysis-service) for the service that will replace it in a few weeks.

**Comment by g-k** [comment]
@vitillo Great! Can we add a deprecation notice to this project's readme in the meantime?

Is someone working on tightening up the CSP on https://github.com/mozilla/telemetry-analysis-service or can I send you a PR for that?

**Comment by mreid-moz** [comment]
@jezdez @maurodoglio You guys interested in a PR for the above CSP goodies?

**Comment by g-k** [comment]
@mreid-moz any word from them?  I can also go ahead with a PR and you can pull in what you want from it.

**Comment by jezdez** [comment]
All, this isn't the right channel to discuss security related issues. Please file a bug with the appropriate flags for confidential tickets for ATMO V2 here: https://mzl.la/2f3Mv36

**Pull request closed without merging**
