### PR TITLE
Add security groups to spark jobs

### PR DESCRIPTION
**Pull request by relud**
requires mozilla-services/svcops#1082

r? @whd

### CODE REVIEW

**Comment by relud** [comment]
for https://bugzilla.mozilla.org/show_bug.cgi?id=1270630

**Comment by relud** [comment]
requirement satisfied

**Comment by whd** [comment]
IIRC you need to specify the security groups by id instead of name in this call, but if it works, LGTM.

There's also https://github.com/mozilla/telemetry-server/blob/master/http/analysis-service/jobs/run.sh which should be updated for scheduled jobs.

**Comment by relud** [comment]
added sg to run.sh, investigating need for sg-id

**Comment by relud** [comment]
confirmed, requires a sg id.

**Comment by relud** [comment]
updated to use security group id

**Comment by relud** [comment]
my attempts to test provisioning with this appear to have worked

**Comment by relud** [comment]
r? again @whd

**Comment by whd** [comment]
Probably adding a new config variable like this should go in https://github.com/mozilla/telemetry-server/blob/master/http/analysis-service/config.py and be referenced by `app.config`.

**Comment by vitillo** [comment]
Note that the analysis service has been [rewritten](https://github.com/mozilla/telemetry-analysis-service) and will soon be deployed in production. If you make changes here, please either file a PR in the new repository or open an issue there.

**Pull request closed without merging**
